version: '3.3'

services:
  oloscreen_node_builder:
    container_name: oloscreen_node_builder
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-build
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
