version: '3.3'

services:

  oloscreen_backend:
    container_name: oloscreen
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/backend'
    ports:
      - 3000:3000
