version: '3.3'

services:
  oloscreen_node:
    container_name: oloscreen_node
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  oloscreen_backend:
    container_name: oloscreen_backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - '.:/app'
      - '/app/backend'
    ports:
      - 3001:3001
